# Generated by Django 2.0 on 2018-05-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='notes',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
