# Generated by Django 2.0 on 2018-05-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0003_auto_20180522_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
